name: Build an image with the static HTML
run-name: ${{ github.actor }} testing build with Hugo.
on:
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 1
      - name: Install Hugo
        run: scripts/install_hugo.sh
      - name: Build HTML
        run: |
              ./cache/hugo \
                --panicOnWarning \
                --source ./hugo \
                --destination ../public \
                --baseURL https://test.quaker-kr.de

